services:
  # Database service
  database:
    image: postgres:15-alpine
    container_name: devops-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tabloid
      - POSTGRES_USER=anna
      - POSTGRES_PASSWORD=sletikkehardcoded
    volumes:
      - db_data:/var/lib/postgresql/data

  # Backend API service
  backend:
    build: ./backend
    container_name: devops-backend
    ports:
      - "5000:8080"
    depends_on:
      - database # The backend needs the database
    environment:
      - ConnectionStrings__Default=Host=devops-database;Port=5432;Database=tabloid;Username=postgres;Password=yourpassword

  # Frontend React service
  frontend:
    build: ./frontend
    container_name: devops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend # The frontend needs the backend to function

# Named volumes for data persistence
volumes:
  db_data: 
    driver: local # storage local on my machine