FROM debian:bookworm-slim

# Install PostgreSQL
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    rm -rf /var/lib/apt/lists/*

# Simple script
COPY start.sh /start.sh
RUN chmod +x /start.sh

ENV PGDATA=/var/lib/postgresql/data
EXPOSE 5432

CMD ["/start.sh"]